import "@/styles/globals.css";
import { Inter, Lato, PlayfairDisplay } from "@/styles/font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body
        className={`${Inter.variable} ${Lato.variable} ${PlayfairDisplay.variable}`}
      >
        {children}
      </body>
    </html>
  );
}
