import "@/styles/globals.css";
import { IBMPlexMono, Inter, LibreBaskerville } from "@/styles/font";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }) {
  return (
    <html lang="en">
      <body className={`${Inter.variable} ${IBMPlexMono.variable} ${LibreBaskerville.variable}`}>
        {children}
      </body>
    </html>
  );
}
