import "@/styles/globals.css";
import { Inter, Lato, PlayfairDisplay } from "@/styles/font";
import { Toaster } from "@/ui/toaster";
import { ReactNode } from "react";
import Providers from "./providers";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${Inter.variable} ${Lato.variable} ${PlayfairDisplay.variable}`}
      >
        <Providers>{children}</Providers>
        <Toaster />
      </body>
    </html>
  );
}
