import "@/styles/globals.css";
import { Inter, Lato, PlayfairDisplay } from "@/styles/font";
import { Toaster } from "@/ui/toaster";
import { ReactNode } from "react";
import { ThemeProvider } from "@/ui/theme-provider";
import { SessionProvider } from "next-auth/react";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children }: { children: ReactNode }) {
  return (
    <html lang="en">
      <body
        className={`${Inter.variable} ${Lato.variable} ${PlayfairDisplay.variable}`}
      >
        <ThemeProvider
          attribute="class"
          defaultTheme="system"
          enableSystem
          disableTransitionOnChange
        >
          <SessionProvider>{children}</SessionProvider>
        </ThemeProvider>
        <Toaster />
      </body>
    </html>
  );
}
